stages:
  - build
  - deploy

variables:
  AWS_DEFAULT_REGION: us-west-2
  BUCKET_NAME: fast-docs-bootstrap

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

build_site:
  stage: build
  image: node:8
  script:
    - npm install
    - npm install replace-in-file
    # Ensure our base url matches the folder in s3 so that assets are served properly
    - "npx replace-in-file \"base: ''\" \"base: '/${CI_COMMIT_REF_SLUG}/'\" docs/.vuepress/config.js"
    - npm run docs:build
  artifacts:
    paths:
      - public

deploy_s3:
  stage: deploy
  image: python:latest
  dependencies:
    - build_site
  before_script:
    - pip install awscli
  script:
    - aws s3 cp public s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}
    on_stop: clean_s3 # clean up s3 manually or when branch is deleted/merged

clean_s3:
  stage: deploy
  image: python:latest
  before_script:
    - pip install awscli
  script:
    - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    action: stop
  when: manual
