# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.fso.arizona.edu/FAST/fso-bootstrap

image: node:9.11.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run docs:build
  artifacts:
    paths:
    - public
  only:
  - master
