stages:
  - deploy

variables:
  AWS_DEFAULT_REGION: us-west-2
  CDN_BUCKET_NAME: fastdev
  DOCS_BUCKET_NAME: fast-docs-bootstrap
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
    - .cache

# ---------------------
# PUBLISH ASSETS TO CDN
# ---------------------

# These jobs do the following:
#  - publish_cdn_version: deploy any tag to `<tagname>`
#  - publish_cdn_next: deploy develop to `@next`
#  - publish_cdn_latest: deploy master to the root of the cdn

# NOTE: Assets will need to be packaged locally before deploying to gitlab

# Tags -> tag in cdn (i.e. `x.x.x`)
publish_cdn_version:
  stage: deploy
  image: python:latest
  only:
    - tags
  script:
    - pip install awscli
    - aws s3 cp dist s3://${CDN_BUCKET_NAME}/assets/${CI_PROJECT_NAME}/${CI_COMMIT_TAG_NAME} --recursive --exclude "*" --include "bootstrap.*"

# Develop -> @next in cdn
publish_cdn_next:
  stage: deploy
  image: python:latest
  only:
    refs:
      - develop
  script:
    - pip install awscli
    - aws s3 cp dist s3://${CDN_BUCKET_NAME}/assets/${CI_PROJECT_NAME}/@next --recursive --exclude "*" --include "bootstrap.*"

# Master -> root of cdn
publish_cdn_release:
  stage: deploy
  image: python:latest
  only:
    refs:
      - master
  script:
    - pip install awscli
    - aws s3 cp dist s3://${CDN_BUCKET_NAME}/assets/${CI_PROJECT_NAME}/ --recursive --exclude "*" --include "bootstrap.*"
