pages:
  stage: deploy
  image: ruby:2.3
  script:
    - curl -sL https://deb.nodesource.com/setup_6.x | bash -
    - apt-get install -y locales nodejs
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8
    - npm install
    - npm install -g grunt-cli bower
    - bower install --allow-root
    - gem install bundler
    - bundle install
    - npm run build
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
